networks:

  microservicios-network:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: mysql-microservicios
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s
    networks:
      - microservicios-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Servicio_Credencial?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservicios-network

  microservicio-monopatin:
    build:
      context: ./microservicio-monopatin
      dockerfile: Dockerfile
    container_name: microservicio-monopatin
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Microservicio_Monopatin?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
          condition: service_healthy
    networks:
      - microservicios-network

  microservicio-pago:
    build:
      context: ./microservicio-pago
      dockerfile: Dockerfile
    container_name: microservicio-pago
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Microservicio_Pago?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservicios-network

  microservicio-parada:
    build:
      context: ./microservicio-parada
      dockerfile: Dockerfile
    container_name: microservicio-parada
    ports:
      - "8003:8003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Microservicio_Parada?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservicios-network

  microservicio-usuario:
    build:
      context: ./microservicio-usuario
      dockerfile: Dockerfile
    container_name: microservicio-usuario
    ports:
      - "8004:8004"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Microservicio_Usuario?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservicios-network

  microservicio-viaje:
    build:
      context: ./microservicio-viaje
      dockerfile: Dockerfile
    container_name: microservicio-viaje
    ports:
      - "8005:8005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Microservicio_Viaje?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservicios-network

volumes:
  mysql_data:
